code_essence/config/routes.rb
CodeEssence::Application.routes.draw do
  resources :lex_minsets

  resources :queries

  resources :function_lex_features

  resources :functions

  resources :lex_features

  resources :min4_features

  resources :java_files

  get "search" => "search#index", as: 'search'
  get "search/get_file_contents" => "search#get_file_contents"
  get "search/get_example_queries" => "search#get_example_queries"
  get "search/get_random_query" => "search#get_random_query"
  get "search/get_suggestions" => "search#get_suggestions"

  post "summarizer/summarize" => "summarizer#summarize", as: 'summarize'

  get "welcome/index"

  root 'welcome#index'

end

code_essence/app/models/function_lex_feature.rb
class FunctionLexFeature < ActiveRecord::Base
	belongs_to :function
	self.primary_key = :function_id
end

code_essence/app/controllers/function_lex_features_controller.rb
class FunctionLexFeaturesController < ApplicationController
  before_action :set_function_lex_feature, only: [:show, :edit, :update, :destroy]

  # GET /function_lex_features
  # GET /function_lex_features.json
  def index
		@search = FunctionLexFeature.search(params[:q])
    @function_lex_features = @search.result.order('function_id').paginate(:page => params[:page])
  end

  # GET /function_lex_features/1
  # GET /function_lex_features/1.json
  def show
		@feature_ids = @function_lex_feature.feature_ids.paginate(:page => params[:page])
  end

  # GET /function_lex_features/new
  def new
    @function_lex_feature = FunctionLexFeature.new
  end

  # GET /function_lex_features/1/edit
  def edit
  end

  # POST /function_lex_features
  # POST /function_lex_features.json
  def create
    @function_lex_feature = FunctionLexFeature.new(function_lex_feature_params)

    respond_to do |format|
      if @function_lex_feature.save
        format.html { redirect_to @function_lex_feature, notice: 'Function lex feature was successfully created.' }
        format.json { render action: 'show', status: :created, location: @function_lex_feature }
      else
        format.html { render action: 'new' }
        format.json { render json: @function_lex_feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /function_lex_features/1
  # PATCH/PUT /function_lex_features/1.json
  def update
    respond_to do |format|
      if @function_lex_feature.update(function_lex_feature_params)
        format.html { redirect_to @function_lex_feature, notice: 'Function lex feature was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @function_lex_feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /function_lex_features/1
  # DELETE /function_lex_features/1.json
  def destroy
    @function_lex_feature.destroy
    respond_to do |format|
      format.html { redirect_to function_lex_features_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_function_lex_feature
      @function_lex_feature = FunctionLexFeature.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def function_lex_feature_params
      params[:function_lex_feature]
    end
end

code_essence/app/helpers/function_lex_features_helper.rb
module FunctionLexFeaturesHelper
end

code_essence/app/views/function_lex_features/_form.html.erb
<%= form_for(@function_lex_feature) do |f| %>
  <% if @function_lex_feature.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@function_lex_feature.errors.count, "error") %> prohibited this function_lex_feature from being saved:</h2>

      <ul>
      <% @function_lex_feature.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

code_essence/app/views/function_lex_features/edit.html.erb
<h1>Editing function_lex_feature</h1>

<%= render 'form' %>

<%= link_to 'Show', @function_lex_feature %> |
<%= link_to 'Back', function_lex_features_path %>

code_essence/app/views/function_lex_features/index.html.erb
<h1>Function TO Lex Features</h1>

<%= search_form_for @search, {:class => "form-inline"} do |f| %>
  <div class="form-group">
    <%= f.number_field :function_id_eq, class: "form-control", placeholder: "Function ID" %>
  	<%= f.submit "Search", :class => "btn btn-primary" %>
  </div>
<% end %>

<div class="flickr_pagination">
  <div class="page_info"><%= page_entries_info @function_lex_features %></div>
</div>


<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Function ID</th>
      <th>Lex Feature IDs</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @function_lex_features.each do |function_lex_feature| %>
      <tr>
				<td><%= function_lex_feature.function_id %></td>	
				<td><%= function_lex_feature.feature_ids.map{ |fid| link_to fid, lex_feature_path(fid)}.join(', ').html_safe %></td>	
        <td><%= link_to 'Show', function_lex_feature %></td>
        <td><%= link_to 'Edit', edit_function_lex_feature_path(function_lex_feature) %></td>
        <td><%= link_to 'Destroy', function_lex_feature, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="apple_pagination">
	<div class="page_info"><%= page_entries_info @function_lex_features %></div>
	<%= will_paginate @function_lex_features %> 
</div>

<br>

<%= link_to 'New Function lex feature', new_function_lex_feature_path %>

code_essence/app/views/function_lex_features/new.html.erb
<h1>New function_lex_feature</h1>

<%= render 'form' %>

<%= link_to 'Back', function_lex_features_path %>

code_essence/app/views/function_lex_features/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-striped table-bordered table-condensed">                  
    <tr>                                                                            
      <th>Function ID</th>                                                                   
      <td><%= @function_lex_feature.function_id %></td>                                               
    </tr>                                                                           
                                                                                    
    <tr>                                                                            
      <th>LEX Feature IDs</th>                                                         
      <td>                                                                          
        <%= @function_lex_feature.feature_ids.map{ |fid| link_to fid, lex_feature_path(fid)}.join(', ').html_safe %>
        <div class="flickr_pagination">                                              
          <div class="page_info"><%= page_entries_info @feature_ids %></div>        
          <%= will_paginate @feature_ids %>                                         
        </div>                                                                      
      </td>                                                                         
    </tr>                                                                           
                                                                                    
</table> 

<%= link_to 'Edit', edit_function_lex_feature_path(@function_lex_feature) %> |
<%= link_to 'Back', function_lex_features_path %>