code_essence/config/routes.rb
CodeEssence::Application.routes.draw do
  resources :lex_minsets

  resources :queries

  resources :function_lex_features

  resources :functions

  resources :lex_features

  resources :min4_features

  resources :java_files

  get "search" => "search#index", as: 'search'
  get "search/get_file_contents" => "search#get_file_contents"
  get "search/get_example_queries" => "search#get_example_queries"
  get "search/get_random_query" => "search#get_random_query"
  get "search/get_suggestions" => "search#get_suggestions"

  post "summarizer/summarize" => "summarizer#summarize", as: 'summarize'

  get "welcome/index"

  root 'welcome#index'

end

code_essence/app/models/lex_minset.rb
class LexMinset < ActiveRecord::Base
	self.per_page = 200
	belongs_to :function
end

code_essence/app/controllers/lex_minsets_controller.rb
class LexMinsetsController < ApplicationController
  before_action :set_lex_minset, only: [:show, :edit, :update, :destroy]

  # GET /lex_minsets
  # GET /lex_minsets.json
  def index
		@search = LexMinset.search(params[:q])
    @lex_minsets = @search.result.order('function_id').paginate(:page => params[:page])
  end

  # GET /lex_minsets/1
  # GET /lex_minsets/1.json
  def show
  end

  # GET /lex_minsets/new
  def new
    @lex_minset = LexMinset.new
  end

  # GET /lex_minsets/1/edit
  def edit
  end

  # POST /lex_minsets
  # POST /lex_minsets.json
  def create
    @lex_minset = LexMinset.new(lex_minset_params)

    respond_to do |format|
      if @lex_minset.save
        format.html { redirect_to @lex_minset, notice: 'Lex minset was successfully created.' }
        format.json { render action: 'show', status: :created, location: @lex_minset }
      else
        format.html { render action: 'new' }
        format.json { render json: @lex_minset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lex_minsets/1
  # PATCH/PUT /lex_minsets/1.json
  def update
    respond_to do |format|
      if @lex_minset.update(lex_minset_params)
        format.html { redirect_to @lex_minset, notice: 'Lex minset was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @lex_minset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lex_minsets/1
  # DELETE /lex_minsets/1.json
  def destroy
    @lex_minset.destroy
    respond_to do |format|
      format.html { redirect_to lex_minsets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lex_minset
      @lex_minset = LexMinset.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lex_minset_params
      params.require(:lex_minset).permit(:function_id, :minset, :size)
    end
end

code_essence/app/helpers/lex_minsets_helper.rb
module LexMinsetsHelper
end

code_essence/app/views/lex_minsets/_form.html.erb
<%= form_for(@lex_minset) do |f| %>
  <% if @lex_minset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lex_minset.errors.count, "error") %> prohibited this lex_minset from being saved:</h2>

      <ul>
      <% @lex_minset.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="field">
    <%= f.label :functin_id %><br>
    <%= f.number_field :function_id %>
  </div>

  <div class="field">
    <%= f.label :minset %><br>
    <%= f.number_field :minset %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.number_field :size %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

code_essence/app/views/lex_minsets/edit.html.erb
<h1>Editing lex_minset</h1>

<%= render 'form' %>

<%= link_to 'Show', @lex_minset %> |
<%= link_to 'Back', lex_minsets_path %>

code_essence/app/views/lex_minsets/index.html.erb
<h1>Minsets (LEX)</h1>

<%= search_form_for @search, class: "form-inline" do |f| %>
  <div class="field">
		<%= f.number_field :function_id_eq, class: "form-control", placeholder: "Function ID" %>
    <%= f.number_field :size_gteq, class: "form-control", placeholder: "<= Minset Size "%>
    <%= f.number_field :size_lteq, class: "form-control", placeholder: "Minset Size <="%>
  	<%= f.submit "Search", class: "btn btn-primary" %>
  </div>
<% end %>

<div class="flickr_pagination">
  <div class="page_info"><%= page_entries_info @lex_minsets %></div>
</div>

<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th><%= sort_link @search, :id, "ID" %></th>
      <th><%= sort_link @search, :function_id, "Function ID" %></th>
      <th><%= sort_link @search, :minset, "Minset (Feature IDs)" %></th>
      <th>Minset (Features)</th>
      <th><%= sort_link @search, :size, "Size" %></th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @lex_minsets.each do |lex_minset| %>
      <tr>
        <td><%= lex_minset.id %></td>
        <td><%= link_to lex_minset.function_id, function_path(lex_minset.function_id) %></td>
				<td>
					<%= lex_minset.minset.map{ |feature_id| link_to feature_id, lex_feature_path(feature_id)}.join(', ').html_safe %>
				</td>
				<td>
					<%= lex_minset.minset.map{ |feature_id| link_to LexFeature.find(feature_id).feature, lex_feature_path(feature_id)}.join(', ').html_safe %>
				</td>
        <td><%= lex_minset.size %></td>
        <td><%= link_to 'Show', lex_minset %></td>
        <td><%= link_to 'Edit', edit_lex_minset_path(lex_minset) %></td>
        <td><%= link_to 'Destroy', lex_minset, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="apple_pagination">
	<div class="page_info"><%= page_entries_info @lex_minsets %></div>
	<%= will_paginate @lex_minsets %> 
</div>

<br>

<%= link_to 'New Lex minset', new_lex_minset_path %>

code_essence/app/views/lex_minsets/new.html.erb
<h1>New lex_minset</h1>

<%= render 'form' %>

<%= link_to 'Back', lex_minsets_path %>

code_essence/app/views/lex_minsets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Minset:</strong>
  <%= @lex_minset.minset %>
</p>

<p>
  <strong>Size:</strong>
  <%= @lex_minset.size %>
</p>

<%= link_to 'Edit', edit_lex_minset_path(@lex_minset) %> |
<%= link_to 'Back', lex_minsets_path %>