code_essence/config/routes.rb
CodeEssence::Application.routes.draw do
  resources :lex_minsets

  resources :queries

  resources :function_lex_features

  resources :functions

  resources :lex_features

  resources :min4_features

  resources :java_files

  get "search" => "search#index", as: 'search'
  get "search/get_file_contents" => "search#get_file_contents"
  get "search/get_example_queries" => "search#get_example_queries"
  get "search/get_random_query" => "search#get_random_query"
  get "search/get_suggestions" => "search#get_suggestions"

  post "summarizer/summarize" => "summarizer#summarize", as: 'summarize'

  get "welcome/index"

  root 'welcome#index'

end

code_essence/app/models/function.rb
class Function < ActiveRecord::Base
	belongs_to :java_file
	has_one :function_lex_feature
	has_many :lex_minset

	self.per_page = 100

end

code_essence/app/controllers/functions_controller.rb
class FunctionsController < ApplicationController
  before_action :set_function, only: [:show, :edit, :update, :destroy]

  # GET /functions
  # GET /functions.json
  def index
    @search = Function.search(params[:q])
    @functions = @search.result.order('id').paginate(:page => params[:page])
  end

  # GET /functions/1
  # GET /functions/1.json
  def show
		@feature_ids = @function.function_lex_feature.feature_ids.paginate(:page => params[:page], :per_page => 100)
  end

  # GET /functions/new
  def new
    @function = Function.new
  end

  # GET /functions/1/edit
  def edit
  end

  # POST /functions
  # POST /functions.json
  def create
    @function = Function.new(function_params)

    respond_to do |format|
      if @function.save
        format.html { redirect_to @function, notice: 'Function was successfully created.' }
        format.json { render action: 'show', status: :created, location: @function }
      else
        format.html { render action: 'new' }
        format.json { render json: @function.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /functions/1
  # PATCH/PUT /functions/1.json
  def update
    respond_to do |format|
      if @function.update(function_params)
        format.html { redirect_to @function, notice: 'Function was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @function.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /functions/1
  # DELETE /functions/1.json
  def destroy
    @function.destroy
    respond_to do |format|
      format.html { redirect_to functions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_function
      @function = Function.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def function_params
      params.require(:function).permit(:name, :java_file_id, :start_line, :end_line)
    end
end

code_essence/app/helpers/functions_helper.rb
module FunctionsHelper
end

code_essence/app/views/functions/_form.html.erb
<%= form_for(@function) do |f| %>
  <% if @function.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@function.errors.count, "error") %> prohibited this function from being saved:</h2>

      <ul>
      <% @function.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :java_file_id %><br>
    <%= f.number_field :java_file_id %>
  </div>
  <div class="field">
    <%= f.label :start_line %><br>
    <%= f.number_field :start_line %>
  </div>
  <div class="field">
    <%= f.label :end_line %><br>
    <%= f.number_field :end_line %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

code_essence/app/views/functions/edit.html.erb
<h1>Editing function</h1>

<%= render 'form' %>

<%= link_to 'Show', @function %> |
<%= link_to 'Back', functions_path %>

code_essence/app/views/functions/index.html.erb
<h1>Functions</h1>

<%= search_form_for @search, {:class => "form-inline form-centered"} do |f| %>
  <div class="form-group">
    <%= f.number_field :id_eq, class: "form-control", placeholder: "ID" %>
    <%= f.number_field :java_file_id_eq, class: "form-control", placeholder: "Java File ID" %>
    <%= f.text_field :name_cont, class: "form-control", placeholder: "Name contains" %>
  	<%= f.submit "Search", :class => "btn btn-default, btn-primary"  %>
  </div>
<% end %>

<div class="flickr_pagination">
  <div class="page_info"><%= page_entries_info @functions %></div>
</div>

<table class="table table-striped table-bordered table-condensed">

  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Java file</th>
      <th>Start line</th>
      <th>End line</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @functions.each do |function| %>
      <tr>
        <td><%= function.id %></td>
        <td><%= truncate(function.name, length: 100, omission: '...(continued)') %></td>
        <td><%= link_to function.java_file_id, java_file_path(function.java_file_id) unless function.java_file_id.nil?%></td>
        <td><%= function.start_line %></td>
        <td><%= function.end_line %></td>
        <td><%= link_to 'Show', function %></td>
        <td><%= link_to 'Edit', edit_function_path(function) %></td>
        <td><%= link_to 'Destroy', function, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="apple_pagination">
	<div class="page_info"><%= page_entries_info @functions %></div>
	<%= will_paginate @functions %> 
</div>

<br>

<%= link_to 'New Function', new_function_path %>

code_essence/app/views/functions/new.html.erb
<h1>New function</h1>

<%= render 'form' %>

<%= link_to 'Back', functions_path %>

code_essence/app/views/functions/show.html.erb
<p id="notice"><%= notice %></p>

<% source_code_path = 'public/' %>
<% rel_location = @function.java_file.location %>                                             
<% location = source_code_path + rel_location %>                                    

<h3 class="page-header"><%= @function.name %></h3>
<table class="table table-striped table-bordered table-condensed"> 
	<tr>
		<th>ID</th><td><%= @function.id %></td>
	</tr>
	<tr>
		<th>File</th><td><%= rel_location %></td>
	</tr>
	<tr>
		<th>Start Line</th><td><%= link_to @function.start_line, "#n#{@function.start_line}" %></td>
	</tr>
	<tr>
		<th>End Line</th><td><%= link_to @function.end_line, "#n#{@function.end_line}" %></td>
	</tr>
	<tr>
		<th>Feature IDS</th>
		<td>
			<%= @feature_ids.map{ |feature_id| link_to feature_id, lex_feature_path(feature_id)}.join(', ').html_safe %>
     	<div class="flickr_pagination">                                              
     	<div class="page_info"><%= page_entries_info @feature_ids %></div>        
  			<%= will_paginate @feature_ids %>                                         
  		</div>                                                                      
		</td>  
	</tr>

</table>

<%= raw CodeRay.highlight_file(location, :line_numbers => :table, :highlight_lines => (@function.start_line..@function.end_line) ) %>                               


<%= link_to 'Edit', edit_function_path(@function) %> |
<%= link_to 'Back', functions_path %>