code_essence/config/routes.rb
CodeEssence::Application.routes.draw do
  resources :lex_minsets

  resources :queries

  resources :function_lex_features

  resources :functions

  resources :lex_features

  resources :min4_features

  resources :java_files

  get "search" => "search#index", as: 'search'
  get "search/get_file_contents" => "search#get_file_contents"
  get "search/get_example_queries" => "search#get_example_queries"
  get "search/get_random_query" => "search#get_random_query"
  get "search/get_suggestions" => "search#get_suggestions"

  post "summarizer/summarize" => "summarizer#summarize", as: 'summarize'

  get "welcome/index"

  root 'welcome#index'

end

code_essence/app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

code_essence/app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>                                          
<div class="container-fluid">                                                       
  <div class="navbar-header">                                                       
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>                                
      <span class="icon-bar"></span>                                                
      <span class="icon-bar"></span>                                                
      <span class="icon-bar"></span>                                                
    </button>                                                                       
    <%= link_to 'Code Essence', root_path, class: 'navbar-brand' %>           
  </div>                                                                            
                                                                                    
  <div class="collapse navbar-collapse navbar-right">                                            
    <ul class="nav navbar-nav nav-pills">                                           
      <%= render 'layouts/navigation_links' %>                                      
    </ul>                                                                           
  </div>                                                                            
                                                                                    
</div>  

code_essence/app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>                                            
                                                                                    
<li class="<%= 'active' if current_page?(root_path)%>"><%= link_to 'Home', root_path %></li>

<li class="<%= 'active' if current_page?(functions_path)%>"><%= link_to 'Functions', functions_path %></li>
<li class="<%= 'active' if current_page?(java_files_path)%>"><%= link_to 'Java Files', java_files_path %></li>
                                                                                    
<li class="dropdown <%= 'active' if current_page?(lex_features_path) or current_page?(min4_features_path) %>">
  <a class="dropdown-toggle" data-toggle="dropdown" href="#">Features<span class="caret"></span></a>
  <ul class="dropdown-menu">                                                        
    <li class="<%= 'active' if current_page?(lex_features_path)%>"><%= link_to 'LEX', lex_features_path %></li>
    <li class="<%= 'active' if current_page?(min4_features_path)%>"><%= link_to 'MIN4', min4_features_path %></li>
  </ul>                                                                             
</li>                                                                               

<li class="<%= 'active' if current_page?(function_lex_features_path)%>"><%= link_to 'Function To Lex Features', function_lex_features_path %></li>


<li class="<%= 'active' if current_page?(lex_minsets_path)%>"><%= link_to 'Lex Minsets', lex_minsets_path %></li>

<li class="<%= 'active' if current_page?(queries_path)%>"><%= link_to 'Queries', queries_path %></li>

code_essence/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" style="height:100%;">
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">
	<link rel="shortcut icon" href="../../assets/ico/favicon.ico">

	<title>Code Essence</title>
		<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>   
		<%= csrf_meta_tags %>   

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body style="height:100%;">

		<div class="navbar navbar-inverse navbar-static-top" role="navigation">
			<%= render 'layouts/navigation' %>	
		</div>


    <div id="content_wrapper" style="height:100%; padding:10px;">                                                   
      <%= render 'layouts/messages' %>                                              
      <%= yield %>                                                                  
    </div>   
		
		<!-- <div class="footer navbar-static-bottom navbar-default">
			<p>&copy; UC Davis 2014</p>
		</div>
    -->

    </div> <!-- /container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
  </body>
</html>